site_name: Awesome Scripts
theme:
  name: material
  logo: assets/favicon-faded-5.svg
  favicon: assets/favicon-white-background.svg
  language: zh
  repo: fontawesome/brands/git-alt
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - announce.dismiss
    # - navigation.footer
    - navigation.tabs
    - navitation.sections
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference 
extra_css:
  - stylesheets/extra.css
repo_url: https://github.com/ricolxwz/awesome-scripts
repo_name: ricolxwz/awesome-scripts