site_name: Awesome Scripts
site_author: ricolxwz
copyright: Copyright &copy; 2024 ricolxwz
site_description: A collection of useful scripts for daily use
repo_url: https://github.com/ricolxwz/awesome-scripts
repo_name: ricolxwz/awesome-scripts
theme:
  name: material
  logo: assets/favicon-faded-8.svg
  favicon: assets/favicon-white-background.svg
  language: zh
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    # - header.autohide
    # - announce.dismiss
    # - navigation.footer
    - navigation.tabs
    - navitation.sections
    - navigation.expand
    - navigation.indexes
    # - navigation.top
    - navigation.tracking
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference 
  icon:
    admonition:
      question: material/new-box
    repo: fontawesome/brands/github-alt
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ricolxwz
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/ricolxwz
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/ricolxwz
  generator: false
extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css
extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.magiclink
  - admonition
  - attr_list
  - md_in_html
  - footnotes
  - def_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
  - search
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      languages:
        - locale: zh
          name: 简体中文
          build: true
          default: true
        - locale: en
          name: English
          build: true
          default: false
          nav_translations:
            开始: Home
      reconfigure_material: true
      reconfigure_search: true
nav:
  - 开始:
    - index.md
    - 更新日志: changelog.md