---
# 请先确保app桥接网络已经创建

services:

  alist: # 5244
    container_name: alist
    hostname: alist
    image: 'xhofe/alist:latest'
    restart: unless-stopped
    volumes:
      - /root/app/alist:/opt/alist/data
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=UTC
    networks:
      - app

  chatgpt-next-web: # 3000
    container_name: chatgpt-next-web
    hostname: chatgpt-next-web
    image: yidadaa/chatgpt-next-web
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - GOOGLE_API_KEY=$GOOGLE_API_KEY
      - ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY
      - CODE=$CODE
    restart: unless-stopped
    networks:
      - app

  umami: # 3000
    container_name: umami
    hostname: umami
    image: ghcr.io/umami-software/umami:postgresql-latest
    environment:
      DATABASE_URL: postgresql://umami:${POSTGRES_PASSWORD}@umami-db:5432/umami
      DATABASE_TYPE: postgresql
      APP_SECRET: replace-me-with-a-random-string
    depends_on:
      umami-db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app
  umami-db: # 5432
    container_name: umami-db
    hostname: umami-db
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - /root/app/umami-db:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app
      
  uptime-kuma: # 3001
    container_name: uptime-kuma
    hostname: uptime-kuma
    image: louislam/uptime-kuma:1
    volumes:
      - /root/app/uptime-kuma:/app/data
    restart: unless-stopped
    networks:
      - app
      
  memos: # 5230
    container_name: memos
    hostname: memos
    image: neosmemo/memos:stable
    volumes:
      - /root/app/memos:/var/opt/memos
    restart: unless-stopped
    networks:
      - app

  yourls: # 80
    container_name: yourls
    hostname: yourls
    image: yourls
    restart: unless-stopped
    environment:
      YOURLS_DB_HOST: yourls-db
      YOURLS_DB_USER: yourls
      YOURLS_DB_PASS: $MYSQL_PASSWORD
      YOURLS_DB_NAME: yourls
      YOURLS_USER: $YOURLS_USER
      YOURLS_PASS: $YOURLS_PASS
      YOURLS_SITE: $YOURLS_SITE
      YOURLS_HOURS_OFFSET: 8
    volumes:
      - /root/app/yourls/:/var/www/html   
    networks:
      - app
  yourls-db:
    container_name: yourls-db
    hostname: yourls-db
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=yourls
      - MYSQL_USER=yourls
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    volumes:
      - /root/app/yourls-db/db:/var/lib/mysql
      - /root/app/yourls-db/conf:/etc/mysql/conf.d
    restart: unless-stopped
    networks:
      - app
      
  nav: # 80
    container_name: nav
    hostname: nav
    image: nginx
    restart: unless-stopped
    volumes:
      - /root/app/nav:/usr/share/nginx/html:ro
    networks:
      - app

  gitlab: # 7750 GIT
    container_name: gitlab
    hostname: gitlab
    image: gitlab/gitlab-ce:17.2.1-ce.0
    restart: unless-stopped
    ports:
      - '7750:22'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['gitlab_shell_ssh_port'] = 7750
        letsencrypt['enabled'] = false
        nginx['enable'] = true
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
    volumes:
      - '/root/app/gitlab/config:/etc/gitlab'
      - '/root/app/gitlab/logs:/var/log/gitlab'
      - '/root/app/gitlab/data:/var/opt/gitlab'
    shm_size: '256m'
    networks:
      - app
  gitlab-runner:
    container_name: gitlab-runner
    hostname: gitlab-runner
    image: gitlab/gitlab-runner:v17.2.1
    restart: unless-stopped
    depends_on:
      - gitlab
    volumes:
     - /root/app/gitlab-runner/config:/etc/gitlab-runner
     - /var/run/docker.sock:/var/run/docker.sock
    networks:
        - app

  easyimage: # 80
    container_name: easyimage
    hostname: easyimage
    image: ddsderek/easyimage:latest
    volumes:
      - '/root/app/easyimage/config:/app/web/config'
      - '/root/app/easyimage/i:/app/web/i'
    restart: unless-stopped
    networks:
      - app

  excalidraw: # 80
    container_name: excalidraw
    hostname: excalidraw
    image: excalidraw/excalidraw:latest
    restart: unless-stopped
    networks:
      - app
  
networks:

  app:
    external: true
