---
# 请先确保app桥接网络已经创建

services:

  nginx-proxy-manager:
      image: 'jc21/nginx-proxy-manager:latest'
      restart: always
      ports:
        - '80:80'
        - '443:443'
        - '7750:7750'
        # - '81:81'
      volumes:
        - /root/nginx/data:/data
        - /root/nginx/letsencrypt:/etc/letsencrypt
      networks:
        - app
        
  portainer: # 9443
    image: portainer/portainer-ce:latest
      volumes:
        - /root/portainer:/data
        - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - app

networks:
  app:
    external: true
