---

services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
    networks:
      - app
  alist: # 5244
    image: 'xhofe/alist:latest'
    restart: always
    volumes:
      - './alist:/opt/alist/data'
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=UTC
    networks:
      - app
  chatgpt-next-web: # 3000
    image: yidadaa/chatgpt-next-web
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - GOOGLE_API_KEY=$GOOGLE_API_KEY
      - ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY
      - CODE=$CODE
    networks:
      - app
  umami: # 3000
    image: ghcr.io/umami-software/umami:postgresql-latest
    environment:
      DATABASE_URL: postgresql://umami:${POSTGRES_PASSWORD}@umami-db:5432/umami
      DATABASE_TYPE: postgresql
      APP_SECRET: replace-me-with-a-random-string
    depends_on:
      umami-db:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app
  umami-db: # 5432
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./umami-db:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app
  uptime-kuma: # 3001
    image: louislam/uptime-kuma:1
    volumes:
      - ./uptime-kuma:/app/data
    restart: unless-stopped
    networks:
      - app
networks:
  app:
    driver: bridge
