---
# 请先确保app桥接网络已经创建

services:

  3x-ui: # 2053
    image: ghcr.io/mhsanaei/3x-ui:latest
    restart: unless-stopped
    volumes:
      - ./app/3x-ui/:/etc/x-ui/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
    tty: true
    networks:
      - app
      
networks:
  app:
    external: true
