---

services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./app/nginx/data:/data
      - ./app/nginx/letsencrypt:/etc/letsencrypt
    networks:
      - app
  3x-ui: # 2053
    image: ghcr.io/mhsanaei/3x-ui:latest
    restart: unless-stopped
    volumes:
      - ./app/3x-ui/:/etc/x-ui/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
    tty: true
    networks:
      - app
networks:
  app:
    driver: bridge
