services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
    networks:
      - app
  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    restart: unless-stopped
    volumes:
      - ./3x-ui/:/etc/x-ui/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
    tty: true
    networks:
      - app
  alist:
    image: 'xhofe/alist:latest'
    restart: always
    volumes:
      - './alist:/opt/alist/data'
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=UTC
    networks:
      - app
networks:
  app:
    driver: bridge