---
# 请先确保app桥接网络已经创建

services:
  nginx-proxy-manager:
      container_name: npm
      hostname: npm
      image: 'jc21/nginx-proxy-manager:latest'
      restart: always
      extra_hosts:
        - "host.docker.internal:<app网络中主机的ip>"
      ports:
        - '80:80'
        - '443:443'
        # - '81:81'
      volumes:
        - /root/man/nginx/data:/data
        - /root/man/nginx/letsencrypt:/etc/letsencrypt
      networks:
        - app
  # portainer: # 9443
  #   container_name: portainer
  #   hostname: portainer
  #   image: portainer/portainer-ce:latest
  #   volumes:
  #     - /root/man/portainer:/data
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   restart: always
  #   networks:
  #     - app

networks:
  app:
    external: true
